services:
  backend:
    container_name: turbo-app-starter-backend
    restart: always
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - turbo_app_starter_network

networks:
  turbo_app_starter_network:
